DECLARE @I AS INT=0
WHILE @I<100000
BEGIN
DECLARE @NAME AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(1)
DECLARE @SURNAME AS VARCHAR(100)
DECLARE @CITY AS VARCHAR(100)
DECLARE @TOWN AS VARCHAR(100)
DECLARE @BIRHDATE AS DATETIME

DECLARE @RAND AS INT

--RASTGELE BiR NAME SEÇER
SET @RAND = RAND()*609
SELECT @NAME = NAME, @GENDER=GENDER FROM NAMES WHERE ID = @RAND

--RASTGELE BİR SOYAD SEÇER
SET @RAND = RAND()*16000
SELECT @SURNAME = SURNAME FROM SURNAMES WHERE ID = @RAND

--RASTGELE BİR ŞEHİR BİLGİSİ SEÇER
SET @RAND = RAND()*900
SELECT @CITY = CITY, @TOWN = TOWN FROM CITY_DISTRICT WHERE ID = @RAND

-- 80 YIL İÇERİSİNDEN BİR TARİH SEÇER
SET @RAND = RAND()*365*80
SET @BIRHDATE = GETDATE()-@RAND

INSERT INTO dbo.CUSTOMERS(NAME,SURNAME,BIRTHDATE,CITY,TOWN,GENDER)
VALUES (@NAME,@SURNAME,@BIRHDATE,@CITY,@TOWN,@GENDER)

SET @I = @I + 1
END

SELECT * FROM CUSTOMERS